// Generated by `node scripts/generate-dom.js`. Do not edit.

import * as $ from "svelte/internal/client";

function increment(_, count) {
	count(count() + 1);
}

var root = $.template(`<button> </button>`);

export default function Input($$anchor, $$props) {
	let count = $.prop($$props, "count", 7, 10);
	var button = root();

	button.__click = [increment, count];

	var text = $.child(button);

	$.reset(button);

	$.template_effect(() => $.set_text(text, `Clicked ${(count() || 0) ?? ""}
  ${(count() == 1 ? "time" : "times") ?? ""}`));

	$.append($$anchor, button);
}

$.delegate(["click"]);