package lexer_test

import (
	"bytes"
	"testing"

	"github.com/livebud/duo/internal/lexer"
	"github.com/matthewmueller/diff"
)

func lex(input string) string {
	return lexer.Print(input)
}

func equal(t testing.TB, input, expected string) {
	t.Helper()
	actual := lex(input)
	if actual == expected {
		return
	}
	var b bytes.Buffer
	b.WriteString("\n\x1b[4mInput\x1b[0m:\n")
	b.WriteString(input)
	b.WriteString("\n\x1b[4mExpected\x1b[0m:\n")
	b.WriteString(expected)
	b.WriteString("\n\n")
	b.WriteString("\x1b[4mActual\x1b[0m: \n")
	b.WriteString(actual)
	b.WriteString("\n\n")
	b.WriteString("\x1b[4mDifference\x1b[0m: \n")
	b.WriteString(diff.String(expected, actual))
	b.WriteString("\n")
	t.Fatal(b.String())
}

func TestEOF(t *testing.T) {
	// is := is.New(t)
	equal(t, ``, `end_of_input`)
}

// Based on: https://github.com/sveltejs/svelte/tree/master/test/parser/samples
// Generated with: scripts/generate-lexer-tests.js
func TestSample(t *testing.T) {
	equal(t, "<input use:autofocus>\n", `less_than identifier:"input" space colon_identifier:"use:autofocus" greater_than space end_of_input`)                                                                                                                                                                                                                                                                                                                     // action <input use:autofocus>\n
	equal(t, "<input use:autofocus use:autofocus>", `less_than identifier:"input" space colon_identifier:"use:autofocus" space colon_identifier:"use:autofocus" greater_than end_of_input`)                                                                                                                                                                                                                                                                        // action-duplicate <input use:autofocus use:autofocus>
	equal(t, "<input use:tooltip=\"{t('tooltip msg')}\">\n", `less_than identifier:"input" space colon_identifier:"use:tooltip" equal quote open_curly expr:"t('tooltip msg')" close_curly quote greater_than space end_of_input`)                                                                                                                                                                                                                                 // action-with-call <input use:tooltip=\"{t('tooltip msg')}\">\n
	equal(t, "<input use:tooltip={message}>\n", `less_than identifier:"input" space colon_identifier:"use:tooltip" equal open_curly expr:"message" close_curly greater_than space end_of_input`)                                                                                                                                                                                                                                                                   // action-with-identifier <input use:tooltip={message}>\n
	equal(t, "<input use:tooltip=\"{'tooltip msg'}\">\n", `less_than identifier:"input" space colon_identifier:"use:tooltip" equal quote open_curly expr:"'tooltip msg'" close_curly quote greater_than space end_of_input`)                                                                                                                                                                                                                                       // action-with-literal <input use:tooltip=\"{'tooltip msg'}\">\n
	equal(t, "{#each things as thing (thing)}\n\t<div animate:flip>flips</div>\n{/each}", `open_curly_hash identifier:"each" expr:"things" space identifier:"as" space identifier:"thing" space open_paren expr:"thing" close_paren close_curly space less_than identifier:"div" space colon_identifier:"animate:flip" greater_than text:"flips" less_than_slash identifier:"div" greater_than space open_curly_slash identifier:"each" close_curly end_of_input`) // animation {#each things as thing (thing)}\n\t<div animate:flip>flips</div>\n{/each}
	equal(t, "<div class:foo={isFoo}></div>", `less_than identifier:"div" space colon_identifier:"class:foo" equal open_curly expr:"isFoo" close_curly greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                                                                                                                   // attribute-class-directive <div class:foo={isFoo}></div>
	equal(t, "<a href=https://www.google.com>Google</a>\n", `less_than identifier:"a" space identifier:"href" equal text:"https://www.google.com" greater_than text:"Google" less_than_slash identifier:"a" greater_than space end_of_input`)                                                                                                                                                                                                                      // attribute-containing-solidus <a href=https://www.google.com>Google</a>\n
	// equal(t, "<input foo=a{1} />\n",``)                                                                                                                                                                                                                                                   // attribute-curly-bracket <input foo=a{1} />\n
	equal(t, "<div style='color: {color};'>{color}</div>\n", `less_than identifier:"div" space identifier:"style" equal quote text:"color: " open_curly expr:"color" close_curly text:";" quote greater_than open_curly expr:"color" close_curly less_than_slash identifier:"div" greater_than space end_of_input`)                                                                      // attribute-dynamic <div style='color: {color};'>{color}</div>\n
	equal(t, "<textarea readonly={readonly}></textarea>\n", `less_than identifier:"textarea" space identifier:"readonly" equal open_curly expr:"readonly" close_curly greater_than less_than_slash identifier:"textarea" greater_than space end_of_input`)                                                                                                                               // attribute-dynamic-boolean <textarea readonly={readonly}></textarea>\n
	equal(t, "<div a=\"\" b={''} c='' d=\"{''}\" ></div>", `less_than identifier:"div" space identifier:"a" equal quote quote space identifier:"b" equal open_curly expr:"''" close_curly space identifier:"c" equal quote quote space identifier:"d" equal quote open_curly expr:"''" close_curly quote space greater_than less_than_slash identifier:"div" greater_than end_of_input`) // attribute-empty <div a=\"\" b={''} c='' d=\"{''}\" ></div>
	// equal(t, "<div class= ></div>",``)                                                                                                                                                                                                                                                    // attribute-empty-error <div class= ></div>
	equal(t, "<div data-foo='semi:&quot;space:&quot letter:&quote number:&quot1 end:&quot'></div>\n", `less_than identifier:"div" space dash_identifier:"data-foo" equal quote text:"semi:&quot;space:&quot letter:&quote number:&quot1 end:&quot" quote greater_than less_than_slash identifier:"div" greater_than space end_of_input`) // attribute-escaped <div data-foo='semi:&quot;space:&quot letter:&quote number:&quot1 end:&quot'></div>\n
	equal(t, "<div id='x' class='y'></div>", `less_than identifier:"div" space identifier:"id" equal quote text:"x" quote space identifier:"class" equal quote text:"y" quote greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                  // attribute-multiple <div id='x' class='y'></div>
	equal(t, "<div {id}/>", `less_than identifier:"div" space open_curly expr:"id" close_curly slash_greater_than end_of_input`)                                                                                                                                                                                                         // attribute-shorthand <div {id}/>
	equal(t, "<div class='foo'></div>", `less_than identifier:"div" space identifier:"class" equal quote text:"foo" quote greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                      // attribute-static <div class='foo'></div>
	equal(t, "<textarea readonly></textarea>", `less_than identifier:"textarea" space identifier:"readonly" greater_than less_than_slash identifier:"textarea" greater_than end_of_input`)                                                                                                                                               // attribute-static-boolean <textarea readonly></textarea>
	equal(t, "<div style=\"color: red;\">red</div>", `less_than identifier:"div" space identifier:"style" equal quote text:"color: red;" quote greater_than text:"red" less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                      // attribute-style <div style=\"color: red;\">red</div>
	equal(t, "<div style:color={myColor}></div>", `less_than identifier:"div" space colon_identifier:"style:color" equal open_curly expr:"myColor" close_curly greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                 // attribute-style-directive <div style:color={myColor}></div>
	// equal(t, "<div style:color|important={myColor}></div>",``)                                                                                                                                                                                                                            // attribute-style-directive-modifiers <div style:color|important={myColor}></div>
	equal(t, "<div style:color></div>", `less_than identifier:"div" space colon_identifier:"style:color" greater_than less_than_slash identifier:"div" greater_than end_of_input`) // attribute-style-directive-shorthand <div style:color></div>
	// equal(t, "<div style:color=\"red\"></div>\n<div style:color='red'></div>\n<div style:color=red></div>\n<div style:color=\"red{variable}\"></div>\n<div style:color='red{variable}'></div>\n<div style:color=red{variable}></div>\n<div style:color={`template${literal}`}></div>", ``) // attribute-style-directive-string <div style:color=\"red\"></div>\n<div style:color='red'></div>\n<div style:color=red></div>\n<div style:color=\"red{variable}\"></div>\n<div style:color='red{variable}'></div>\n<div style:color=red{variable}></div>\n<div style:color={`template${literal}`}></div>
	equal(t, "<Widget foo={42} bind:foo/>", `less_than upper_identifier:"Widget" space identifier:"foo" equal open_curly expr:"42" close_curly space colon_identifier:"bind:foo" slash_greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // attribute-unique-binding-error <Widget foo={42} bind:foo/>
	equal(t, "<div class='foo' class='bar'></div>", `less_than identifier:"div" space identifier:"class" equal quote text:"foo" quote space identifier:"class" equal quote text:"bar" quote greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // attribute-unique-error <div class='foo' class='bar'></div>
	equal(t, "<div title='foo' {title}></div>", `less_than identifier:"div" space identifier:"title" equal quote text:"foo" quote space open_curly expr:"title" close_curly greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // attribute-unique-shorthand-error <div title='foo' {title}></div>
	equal(t, "<div class=foo></div>", `less_than identifier:"div" space identifier:"class" equal text:"foo" greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // attribute-unquoted <div class=foo></div>
	equal(t, "<button on:click= {foo}>Click</button>\n", `less_than identifier:"button" space colon_identifier:"on:click" equal space open_curly expr:"foo" close_curly greater_than text:"Click" less_than_slash identifier:"button" greater_than space end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // attribute-with-whitespace <button on:click= {foo}>Click</button>\n
	equal(t, "{#await thePromise}\n\t<p>loading...</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}", `open_curly_hash identifier:"await" expr:"thePromise" close_curly space less_than identifier:"p" greater_than text:"loading..." less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"catch" expr:"theError" close_curly space less_than identifier:"p" greater_than text:"oh no! " open_curly expr:"theError.message" close_curly less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"await" close_curly end_of_input`)                                                                                                                                                                                                                                                                              // await-catch {#await thePromise}\n\t<p>loading...</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}
	equal(t, "{#await thePromise}\n\t<p>loading...</p>\n{:then theValue}\n\t<p>the value is {theValue}</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}", `open_curly_hash identifier:"await" expr:"thePromise" close_curly space less_than identifier:"p" greater_than text:"loading..." less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"then" expr:"theValue" close_curly space less_than identifier:"p" greater_than text:"the value is " open_curly expr:"theValue" close_curly less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"catch" expr:"theError" close_curly space less_than identifier:"p" greater_than text:"oh no! " open_curly expr:"theError.message" close_curly less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"await" close_curly end_of_input`) // await-then-catch {#await thePromise}\n\t<p>loading...</p>\n{:then theValue}\n\t<p>the value is {theValue}</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}
	equal(t, "<script>\n\tlet name;\n</script>\n\n<input bind:value={name}>", `less_than identifier:"script" greater_than script:"\n\tlet name;\n" less_than_slash identifier:"script" greater_than space less_than identifier:"input" space colon_identifier:"bind:value" equal open_curly expr:"name" close_curly greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // binding <script>\n\tlet name;\n</script>\n\n<input bind:value={name}>
	equal(t, "<script>\n\tlet foo;\n</script>\n\n<Widget bind:foo/>", `less_than identifier:"script" greater_than script:"\n\tlet foo;\n" less_than_slash identifier:"script" greater_than space less_than upper_identifier:"Widget" space colon_identifier:"bind:foo" slash_greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // binding-shorthand <script>\n\tlet foo;\n</script>\n\n<Widget bind:foo/>
	equal(t, "<!-- a comment -->", `comment:"<!-- a comment -->" end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // comment <!-- a comment -->
	equal(t, "<!-- svelte-ignore foo bar -->", `comment:"<!-- svelte-ignore foo bar -->" end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // comment-with-ignores <!-- svelte-ignore foo bar -->
	// equal(t, "<svelte:component this=\"{foo ? Foo : Bar}\"></svelte:component>",``)                                                                                                                                                                                                       // component-dynamic <svelte:component this=\"{foo ? Foo : Bar}\"></svelte:component>
	// equal(t, "Hello &amp; World", `text:"Hello & World" end_of_input`) // convert-entities Hello &amp; World
	// equal(t, "<p>Hello &amp; World</p>", `less_than identifier:"p" greater_than text:"Hello & World" less_than_slash identifier:"p" greater_than end_of_input`) // convert-entities-in-element <p>Hello &amp; World</p>
	// equal(t, "<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>", ``) // css <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>
	// equal(t, "<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n",``)                                                                                                                                                                                                   // css-option-none <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n
	// equal(t, "<svelte:element this=\"div\"></svelte:element>\n<svelte:element this=\"div\" class=\"foo\"></svelte:element>",``)                                                                                                                                                           // dynamic-element-string <svelte:element this=\"div\"></svelte:element>\n<svelte:element this=\"div\" class=\"foo\"></svelte:element>
	// equal(t, "<svelte:element this={tag}></svelte:element>\n<svelte:element this={tag} class=\"foo\"></svelte:element>",``)                                                                                                                                                               // dynamic-element-variable <svelte:element this={tag}></svelte:element>\n<svelte:element this={tag} class=\"foo\"></svelte:element>
	// equal(t, "<script>\n\timport { onMount } from 'svelte';\n\n\tonMount(() => {\n\t\timport('./foo.js').then(foo => {\n\t\t\tconsole.log(foo.default);\n\t\t});\n\t});\n</script>",``)                                                                                                   // dynamic-import <script>\n\timport { onMount } from 'svelte';\n\n\tonMount(() => {\n\t\timport('./foo.js').then(foo => {\n\t\t\tconsole.log(foo.default);\n\t\t});\n\t});\n</script>
	equal(t, "{#each animals as animal}\n\t<p>{animal}</p>\n{/each}\n", `open_curly_hash identifier:"each" expr:"animals" space identifier:"as" space identifier:"animal" close_curly space less_than identifier:"p" greater_than open_curly expr:"animal" close_curly less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"each" close_curly space end_of_input`) // each-block {#each animals as animal}\n\t<p>{animal}</p>\n{/each}\n
	// equal(t, "<script>\n\texport let animals;\n</script>\n\n{#each animals as [key, value, ...rest]}\n\t<p>{key}: {value}</p>\n{/each}\n",``)                                                                                                                                             // each-block-destructured <script>\n\texport let animals;\n</script>\n\n{#each animals as [key, value, ...rest]}\n\t<p>{key}: {value}</p>\n{/each}\n
	equal(t, "{#each animals as animal}\n\t<p>{animal}</p>\n{:else}\n\t<p>no animals</p>\n{/each}\n", `open_curly_hash identifier:"each" expr:"animals" space identifier:"as" space identifier:"animal" close_curly space less_than identifier:"p" greater_than open_curly expr:"animal" close_curly less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"else" close_curly space less_than identifier:"p" greater_than text:"no animals" less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"each" close_curly space end_of_input`) // each-block-else {#each animals as animal}\n\t<p>{animal}</p>\n{:else}\n\t<p>no animals</p>\n{/each}\n
	equal(t, "{#each animals as animal, i}\n\t<p>{i}: {animal}</p>\n{/each}\n", `open_curly_hash identifier:"each" expr:"animals" space identifier:"as" space identifier:"animal" comma identifier:"i" close_curly space less_than identifier:"p" greater_than open_curly expr:"i" close_curly text:": " open_curly expr:"animal" close_curly less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"each" close_curly space end_of_input`)                                                                                                                       // each-block-indexed {#each animals as animal, i}\n\t<p>{i}: {animal}</p>\n{/each}\n
	equal(t, "{#each todos as todo (todo.id)}\n\t<p>{todo}</p>\n{/each}\n", `open_curly_hash identifier:"each" expr:"todos" space identifier:"as" space identifier:"todo" space open_paren expr:"todo.id" close_paren close_curly space less_than identifier:"p" greater_than open_curly expr:"todo" close_curly less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"each" close_curly space end_of_input`)                                                                                                                                                    // each-block-keyed {#each todos as todo (todo.id)}\n\t<p>{todo}</p>\n{/each}\n
	equal(t, "<span attr=\"foo\"></span>\n<span attr='bar'></span>\n", `less_than identifier:"span" space identifier:"attr" equal quote text:"foo" quote greater_than less_than_slash identifier:"span" greater_than space less_than identifier:"span" space identifier:"attr" equal quote text:"bar" quote greater_than less_than_slash identifier:"span" greater_than space end_of_input`)                                                                                                                                                                                              // element-with-attribute <span attr=\"foo\"></span>\n<span attr='bar'></span>\n
	equal(t, "<span attr=\"\"></span>\n<span attr=''></span>\n", `less_than identifier:"span" space identifier:"attr" equal quote quote greater_than less_than_slash identifier:"span" greater_than space less_than identifier:"span" space identifier:"attr" equal quote quote greater_than less_than_slash identifier:"span" greater_than space end_of_input`)                                                                                                                                                                                                                          // element-with-attribute-empty-string <span attr=\"\"></span>\n<span attr=''></span>\n
	equal(t, "<h1>hello {name}!</h1>\n", `less_than identifier:"h1" greater_than text:"hello " open_curly expr:"name" close_curly text:"!" less_than_slash identifier:"h1" greater_than space end_of_input`)                                                                                                                                                                                                                                                                                                                                                                              // element-with-mustache <h1>hello {name}!</h1>\n
	equal(t, "<span>test</span>", `less_than identifier:"span" greater_than text:"test" less_than_slash identifier:"span" greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                                                     // element-with-text <span>test</span>
	// equal(t, "<!doctype html>",`LessThanExclamation Identifier:"doctype" Space Identifier:"html" GreaterThan EndOfInput`)                                                                          // elements <!doctype html>
	// equal(t, "{#await true}\n\t{#each foo as bar}\n{:catch f}\n{/await}",``)                                                                                                                                                                                                              // error-catch-before-closing {#await true}\n\t{#each foo as bar}\n{:catch f}\n{/await}
	// equal(t, "{:catch theValue}\n",``)                                                                                                                                                                                                                                                    // error-catch-without-await {:catch theValue}\n
	// equal(t, "<!-- an unclosed comment",``)                                                                                                                                                                                                                                               // error-comment-unclosed <!-- an unclosed comment
	// equal(t, "<style>\n\tthis is not css\n</style>",``)                                                                                                                                                                                                                                   // error-css <style>\n\tthis is not css\n</style>
	// equal(t, "<style>\n\t:global {}\n</style>\n",``)                                                                                                                                                                                                                                      // error-css-global-without-selector <style>\n\t:global {}\n</style>\n
	// equal(t, "{#if true}\n\t<li>\n{:else}\n{/if}",``)                                                                                                                                                                                                                                     // error-else-before-closing {#if true}\n\t<li>\n{:else}\n{/if}
	// equal(t, "{#if true}\n\t{#await p}\n{:else}\n{/if}",``)                                                                                                                                                                                                                               // error-else-before-closing-2 {#if true}\n\t{#await p}\n{:else}\n{/if}
	// equal(t, "<li>\n{:else}",``)                                                                                                                                                                                                                                                          // error-else-before-closing-3 <li>\n{:else}
	// equal(t, "{#if true}\n\t{#await foo}\n{:else if false}\n{/if}",``)                                                                                                                                                                                                                    // error-else-if-before-closing {#if true}\n\t{#await foo}\n{:else if false}\n{/if}
	// equal(t, "{#if true}\n\t<p>\n{:else if false}\n{/if}",``)                                                                                                                                                                                                                             // error-else-if-before-closing-2 {#if true}\n\t<p>\n{:else if false}\n{/if}
	// equal(t, "{#await foo}\n{:then bar}\n\t{:else if}\n{/await}", ``) // error-else-if-without-if {#await foo}\n{:then bar}\n\t{:else if}\n{/await}
	// equal(t, "<span {}></span>",``)                                                                                                                                                                                                                                                       // error-empty-attribute-shorthand <span {}></span>
	// equal(t, "<h1 class:={true}>Hello</h1>\n",``)                                                                                                                                                                                                                                         // error-empty-classname-binding <h1 class:={true}>Hello</h1>\n
	// equal(t, "<h1 use:>Hello</h1>\n",``)                                                                                                                                                                                                                                                  // error-empty-directive-name <h1 use:>Hello</h1>\n
	// equal(t, "{42 = nope}\n",``)                                                                                                                                                                                                                                                          // error-illegal-expression {42 = nope}\n
	// equal(t, "<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n\n<style>\n\tdiv {\n\t\tcolor: blue;\n\t}\n</style>",``)                                                                                                                                                // error-multiple-styles <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n\n<style>\n\tdiv {\n\t\tcolor: blue;\n\t}\n</style>
	// equal(t, "<h1>Hello {name}!</h1>\n\n<script>",``)                                                                                                                                                                                                                                     // error-script-unclosed <h1>Hello {name}!</h1>\n\n<script>
	// equal(t, "<script>\n\n<h1>Hello {name}!</h1>",``)                                                                                                                                                                                                                                     // error-script-unclosed-eof <script>\n\n<h1>Hello {name}!</h1>
	// equal(t, "<svelte:self/>",``)                                                                                                                                                                                                                                                         // error-self-reference <svelte:self/>
	// equal(t, "<h1>Hello {name}!</h1>\n\n<style>",``)                                                                                                                                                                                                                                      // error-style-unclosed <h1>Hello {name}!</h1>\n\n<style>
	// equal(t, "<style>\n\n<h1>Hello {name}!</h1>",``)                                                                                                                                                                                                                                      // error-style-unclosed-eof <style>\n\n<h1>Hello {name}!</h1>
	// equal(t, "{#if x}\n\t<svelte:selfdestructive x=\"{x - 1}\"/>\n{/if}",``)                                                                                                                                                                                                              // error-svelte-selfdestructive {#if x}\n\t<svelte:selfdestructive x=\"{x - 1}\"/>\n{/if}
	// equal(t, "{#await true}\n\t<li>\n{:then f}\n{/await}", ``) // error-then-before-closing {#await true}\n\t<li>\n{:then f}\n{/await}
	// equal(t, "{:then theValue}\n",``)                                                                                                                                                                                                                                                     // error-then-without-await {:then theValue}\n
	// equal(t, "<Component test={{a: 1} />",``)                                                                                                                                                                                                                                             // error-unclosed-attribute-self-close-tag <Component test={{a: 1} />
	// equal(t, "<div>",``)                                                                                                                                                                                                                                                                  // error-unexpected-end-of-input <div>
	// equal(t, "<d",``)                                                                                                                                                                                                                                                                     // error-unexpected-end-of-input-b <d
	// equal(t, "<",``)                                                                                                                                                                                                                                                                      // error-unexpected-end-of-input-c <
	// equal(t, "{#if foo}\n\t<p>foo</p>",``)                                                                                                                                                                                                                                                // error-unexpected-end-of-input-d {#if foo}\n\t<p>foo</p>
	// equal(t, "</div>",``)                                                                                                                                                                                                                                                                 // error-unmatched-closing-tag </div>
	// equal(t, "<p>\n\t<pre>pre tag</pre>\n</p>",``)                                                                                                                                                                                                                                        // error-unmatched-closing-tag-autoclose <p>\n\t<pre>pre tag</pre>\n</p>
	// equal(t, "<div>\n\t<p>\n\t<pre>pre tag</pre>\n</div>\n</p>",``)                                                                                                                                                                                                                       // error-unmatched-closing-tag-autoclose-2 <div>\n\t<p>\n\t<pre>pre tag</pre>\n</div>\n</p>
	equal(t, "<input>this is illegal!</input>", `less_than identifier:"input" greater_than text:"this is illegal!" less_than_slash identifier:"input" greater_than end_of_input`) // error-void-closing <input>this is illegal!</input>
	// equal(t, "<svelte:window>contents</svelte:window>",``)                                                                                                                                                                                                                                // error-window-children <svelte:window>contents</svelte:window>
	// equal(t, "<svelte:window/>\n<svelte:window/>",``)                                                                                                                                                                                                                                     // error-window-duplicate <svelte:window/>\n<svelte:window/>
	// equal(t, "{#if foo}\n\t<svelte:window/>\n{/if}",``)                                                                                                                                                                                                                                   // error-window-inside-block {#if foo}\n\t<svelte:window/>\n{/if}
	// equal(t, "<div>\n\t<svelte:window/>\n</div>",``)                                                                                                                                                                                                                                      // error-window-inside-element <div>\n\t<svelte:window/>\n</div>
	// equal(t, "<button on:click=\"{() => visible = !visible}\">toggle</button>\n\n{#if visible}\n\t<p>hello!</p>\n{/if}\n",``)                                                                                                                                                             // event-handler <button on:click=\"{() => visible = !visible}\">toggle</button>\n\n{#if visible}\n\t<p>hello!</p>\n{/if}\n
	equal(t, "{#if foo}bar{/if}\n", `open_curly_hash identifier:"if" expr:"foo" close_curly text:"bar" open_curly_slash identifier:"if" close_curly space end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                      // if-block {#if foo}bar{/if}\n
	equal(t, "{#if foo}\n\t<p>foo</p>\n{:else}\n\t<p>not foo</p>\n{/if}\n", `open_curly_hash identifier:"if" expr:"foo" close_curly space less_than identifier:"p" greater_than text:"foo" less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"else" close_curly space less_than identifier:"p" greater_than text:"not foo" less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"if" close_curly space end_of_input`)                                                                                    // if-block-else {#if foo}\n\t<p>foo</p>\n{:else}\n\t<p>not foo</p>\n{/if}\n
	equal(t, "{#if x > 10}\n\t<p>x is greater than 10</p>\n{:else if x < 5}\n\t<p>x is less than 5</p>\n{/if}\n", `open_curly_hash identifier:"if" expr:"x > 10" close_curly space less_than identifier:"p" greater_than text:"x is greater than 10" less_than_slash identifier:"p" greater_than space open_curly_colon identifier:"else if" expr:"x < 5" close_curly space less_than identifier:"p" greater_than text:"x is less than 5" less_than_slash identifier:"p" greater_than space open_curly_slash identifier:"if" close_curly space end_of_input`) // if-block-elseif {#if x > 10}\n\t<p>x is greater than 10</p>\n{:else if x < 5}\n\t<p>x is less than 5</p>\n{/if}\n
	// equal(t, "<ul>\n\t<li>a\n\t<li>b\n\t<li>c\n</ul>",``)                                                                                                                                                                                                                                 // implicitly-closed-li <ul>\n\t<li>a\n\t<li>b\n\t<li>c\n</ul>
	// equal(t, "<ul>\n\t<li>a\n\t{#if true}\n\t\t<li>b\n\t{/if}\n\t<li>c\n</ul>\n",``)                                                                                                                                                                                                      // implicitly-closed-li-block <ul>\n\t<li>a\n\t{#if true}\n\t\t<li>b\n\t{/if}\n\t<li>c\n</ul>\n
	// equal(t, "<span>&nbsp;</span>",``)                                                                                                                                                                                                                                                    // nbsp <span>&nbsp;</span>
	// equal(t, "{#if true}\n\t<input>\n{:else}\n{/if}\n\n{#if true}\n\t<br>\n{:else}\n{/if}\n\n{#await true}\n\t<input>\n{:then f}\n{/await}\n\n{#await true}\n\t<br>\n{:then f}\n{/await}",``)                                                                                             // no-error-if-before-closing {#if true}\n\t<input>\n{:else}\n{/if}\n\n{#if true}\n\t<br>\n{:else}\n{/if}\n\n{#await true}\n\t<input>\n{:then f}\n{/await}\n\n{#await true}\n\t<br>\n{:then f}\n{/await}
	// equal(t, "<p> {@html raw1} {@html raw2} </p>\n",``)                                                                                                                                                                                                                                   // raw-mustaches <p> {@html raw1} {@html raw2} </p>\n
	// equal(t, "{@htmlfoo}\n",``)                                                                                                                                                                                                                                                           // raw-mustaches-whitespace-error {@htmlfoo}\n
	equal(t, "<script>\n\tlet foo;\n</script>\n\n<canvas bind:this={foo}></canvas>", `less_than identifier:"script" greater_than script:"\n\tlet foo;\n" less_than_slash identifier:"script" greater_than space less_than identifier:"canvas" space colon_identifier:"bind:this" equal open_curly expr:"foo" close_curly greater_than less_than_slash identifier:"canvas" greater_than end_of_input`)                                                                                       // refs <script>\n\tlet foo;\n</script>\n\n<canvas bind:this={foo}></canvas>
	equal(t, "<script>\n\tlet name = 'world';\n</script>\n\n<h1>Hello {name}!</h1>", `less_than identifier:"script" greater_than script:"\n\tlet name = 'world';\n" less_than_slash identifier:"script" greater_than space less_than identifier:"h1" greater_than text:"Hello " open_curly expr:"name" close_curly text:"!" less_than_slash identifier:"h1" greater_than end_of_input`)                                                                                                     // script <script>\n\tlet name = 'world';\n</script>\n\n<h1>Hello {name}!</h1>
	equal(t, "<script>\n\t// TODO write some code\n</script>\n\n<div></div>", `less_than identifier:"script" greater_than script:"\n\t// TODO write some code\n" less_than_slash identifier:"script" greater_than space less_than identifier:"div" greater_than less_than_slash identifier:"div" greater_than end_of_input`)                                                                                                                                                                // script-comment-only <script>\n\t// TODO write some code\n</script>\n\n<div></div>
	equal(t, "<script>\n\tlet name = 'world';\n\n\t// trailing line comment\n</script>\n\n<h1>Hello {name}!</h1>\n", `less_than identifier:"script" greater_than script:"\n\tlet name = 'world';\n\n\t// trailing line comment\n" less_than_slash identifier:"script" greater_than space less_than identifier:"h1" greater_than text:"Hello " open_curly expr:"name" close_curly text:"!" less_than_slash identifier:"h1" greater_than space end_of_input`)                                 // script-comment-trailing <script>\n\tlet name = 'world';\n\n\t// trailing line comment\n</script>\n\n<h1>Hello {name}!</h1>\n
	equal(t, "<script>\n\tlet name = 'world';\n\n\t/*\n\t\ttrailing multiline comment\n\t*/\n</script>\n\n<h1>Hello {name}!</h1>\n", `less_than identifier:"script" greater_than script:"\n\tlet name = 'world';\n\n\t/*\n\t\ttrailing multiline comment\n\t*/\n" less_than_slash identifier:"script" greater_than space less_than identifier:"h1" greater_than text:"Hello " open_curly expr:"name" close_curly text:"!" less_than_slash identifier:"h1" greater_than space end_of_input`) // script-comment-trailing-multiline <script>\n\tlet name = 'world';\n\n\t/*\n\t\ttrailing multiline comment\n\t*/\n</script>\n\n<h1>Hello {name}!</h1>\n
	equal(t, "<div/>", `less_than identifier:"div" slash_greater_than end_of_input`)                                                                                                                                                                                                                                                                                                                                                                                                        // self-closing-element <div/>
	equal(t, "{#if depth > 1}\n\t<svelte:self depth='{depth - 1}'/>\n{/if}", `open_curly_hash identifier:"if" expr:"depth > 1" close_curly space less_than colon_identifier:"svelte:self" space identifier:"depth" equal quote open_curly expr:"depth - 1" close_curly quote slash_greater_than space open_curly_slash identifier:"if" close_curly end_of_input`)                                                                                                                           // self-reference {#if depth > 1}\n\t<svelte:self depth='{depth - 1}'/>\n{/if}
	equal(t, "<Component><div slot='foo'></div></Component>\n", `less_than upper_identifier:"Component" greater_than less_than identifier:"div" space identifier:"slot" equal quote text:"foo" quote greater_than less_than_slash identifier:"div" greater_than less_than_slash upper_identifier:"Component" greater_than space end_of_input`)                                                                                                                                              // slotted-element <Component><div slot='foo'></div></Component>\n
	equal(t, "<p> {a} {b} : {c} : </p>\n", `less_than identifier:"p" greater_than space open_curly expr:"a" close_curly space open_curly expr:"b" close_curly space text:": " open_curly expr:"c" close_curly space text:": " less_than_slash identifier:"p" greater_than space end_of_input`)                                                                                                                                                                                              // space-between-mustaches <p> {a} {b} : {c} : </p>\n
	equal(t, "<div {...props}></div>\n", `less_than identifier:"div" space open_curly expr:"...props" close_curly greater_than less_than_slash identifier:"div" greater_than space end_of_input`)                                                                                                                                                                                                                                                                                           // spread <div {...props}></div>\n
	equal(t, "<svelte:head><style></style></svelte:head>", `less_than colon_identifier:"svelte:head" greater_than less_than identifier:"style" greater_than less_than_slash identifier:"style" greater_than less_than_slash colon_identifier:"svelte:head" greater_than end_of_input`)                                                                                                                                                                                                      // style-inside-head <svelte:head><style></style></svelte:head>
	equal(t, "<textarea>\n\t<p>not actually an element. {foo}</p>\n</textarea>", `less_than identifier:"textarea" greater_than space less_than identifier:"p" greater_than text:"not actually an element. " open_curly expr:"foo" close_curly less_than_slash identifier:"p" greater_than space less_than_slash identifier:"textarea" greater_than end_of_input`)                                                                                                                           // textarea-children <textarea>\n\t<p>not actually an element. {foo}</p>\n</textarea>
	// equal(t, "<textarea>\n\t<p>not actu </textar ally an element. {foo}</p>\n</textare\n\n\n> </textaread >asdf</textarea\n\n\n</textarea\n\n>\n\n",``)                                                                                                                                   // textarea-end-tag <textarea>\n\t<p>not actu </textar ally an element. {foo}</p>\n</textare\n\n\n> </textaread >asdf</textarea\n\n\n</textarea\n\n>\n\n
	equal(t, "<div in:style=\"{{opacity: 0}}\">fades in</div>", `less_than identifier:"div" space colon_identifier:"in:style" equal quote open_curly expr:"{opacity: 0}" close_curly quote greater_than text:"fades in" less_than_slash identifier:"div" greater_than end_of_input`) // transition-intro <div in:style=\"{{opacity: 0}}\">fades in</div>
	equal(t, "<div in:fade>fades in</div>", `less_than identifier:"div" space colon_identifier:"in:fade" greater_than text:"fades in" less_than_slash identifier:"div" greater_than end_of_input`)                                                                                   // transition-intro-no-params <div in:fade>fades in</div>
	// equal(t, "{#each things as 𐊧}\n\t<p>{𐊧}</p>\n{/each}", ``)                                                                                                                                                                                                                       // unusual-identifier {#each things as 𐊧}\n\t<p>{𐊧}</p>\n{/each}
	// equal(t, "<script>\n\tlet name = 'world';\n</script     \n\n\n\n\n>\n\n<h1>Hello {name}!</h1>",``)                                                                                                                                                                                    // whitespace-after-script-tag <script>\n\tlet name = 'world';\n</script     \n\n\n\n\n>\n\n<h1>Hello {name}!</h1>
	equal(t, "<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style     \n\n\n\n\n>", `less_than identifier:"div" greater_than text:"foo" less_than_slash identifier:"div" greater_than space less_than identifier:"style" greater_than space text:"div " open_curly expr:"\n\t\tcolor: red;\n\t" close_curly space less_than_slash identifier:"style" space greater_than end_of_input`)                                                             // whitespace-after-style-tag <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style     \n\n\n\n\n>
	equal(t, "\n\n\t\t\t\t<p>just chillin' over here</p>", `space less_than identifier:"p" greater_than text:"just chillin' over here" less_than_slash identifier:"p" greater_than end_of_input`)                                                                                                                                                                                                                                                                // whitespace-leading-trailing \n\n\t\t\t\t<p>just chillin' over here</p>
	equal(t, "<h1>Hello <strong>{name}! </strong><span>How are you?</span></h1>\n", `less_than identifier:"h1" greater_than text:"Hello " less_than identifier:"strong" greater_than open_curly expr:"name" close_curly text:"! " less_than_slash identifier:"strong" greater_than less_than identifier:"span" greater_than text:"How are you?" less_than_slash identifier:"span" greater_than less_than_slash identifier:"h1" greater_than space end_of_input`) // whitespace-normal <h1>Hello <strong>{name}! </strong><span>How are you?</span></h1>\n
}
