package lexer_test

import (
	"testing"

	"github.com/livebud/duo/internal/lexer"
	"github.com/matryer/is"
)

func lex(input string) string {
	return lexer.Print(input)
}

func TestEOF(t *testing.T) {
	is := is.New(t)
	is.Equal(lex(``), `EndOfInput`)
}

// Based on: https://github.com/sveltejs/svelte/tree/master/test/parser/samples
// Generated with: scripts/generate-lexer-tests.js
func TestSample(t *testing.T) {
	is := is.New(t)
	is.Equal(lex("<input use:autofocus>\n"), `LessThan Identifier:"input" Space ColonIdentifier:"use:autofocus" GreaterThan Space EndOfInput`)                                                                                   // action <input use:autofocus>\n
	is.Equal(lex("<input use:autofocus use:autofocus>"), `LessThan Identifier:"input" Space ColonIdentifier:"use:autofocus" Space ColonIdentifier:"use:autofocus" GreaterThan EndOfInput`)                                       // action-duplicate <input use:autofocus use:autofocus>
	is.Equal(lex("<input use:tooltip=\"{t('tooltip msg')}\">\n"), `LessThan Identifier:"input" Space ColonIdentifier:"use:tooltip" Equal Quote OpenCurly Text:"t('tooltip msg')" CloseCurly Quote GreaterThan Space EndOfInput`) // action-with-call <input use:tooltip=\"{t('tooltip msg')}\">\n
	is.Equal(lex("<input use:tooltip={message}>\n"), `LessThan Identifier:"input" Space ColonIdentifier:"use:tooltip" Equal OpenCurly Text:"message" CloseCurly GreaterThan Space EndOfInput`)                                   // action-with-identifier <input use:tooltip={message}>\n
	is.Equal(lex("<input use:tooltip=\"{'tooltip msg'}\">\n"), `LessThan Identifier:"input" Space ColonIdentifier:"use:tooltip" Equal Quote OpenCurly Text:"'tooltip msg'" CloseCurly Quote GreaterThan Space EndOfInput`)       // action-with-literal <input use:tooltip=\"{'tooltip msg'}\">\n
	// is.Equal(lex("{#each things as thing (thing)}\n\t<div animate:flip>flips</div>\n{/each}"), ``)                                                                                                                                                                                              // animation {#each things as thing (thing)}\n\t<div animate:flip>flips</div>\n{/each}
	is.Equal(lex("<div class:foo={isFoo}></div>"), `LessThan Identifier:"div" Space ColonIdentifier:"class:foo" Equal OpenCurly Text:"isFoo" CloseCurly GreaterThan LessThanSlash Identifier:"div" GreaterThan EndOfInput`)                 // attribute-class-directive <div class:foo={isFoo}></div>
	is.Equal(lex("<a href=https://www.google.com>Google</a>\n"), `LessThan Identifier:"a" Space Identifier:"href" Equal Text:"https://www.google.com" GreaterThan Text:"Google" LessThanSlash Identifier:"a" GreaterThan Space EndOfInput`) // attribute-containing-solidus <a href=https://www.google.com>Google</a>\n
	// is.Equal(lex("<input foo=a{1} />\n"), ``)                                                                                                                                                                                                                                                   // attribute-curly-bracket <input foo=a{1} />\n
	// is.Equal(lex("<div style='color: {color};'>{color}</div>\n"), ``)                                                                                                                                                                                                                           // attribute-dynamic <div style='color: {color};'>{color}</div>\n
	// is.Equal(lex("<textarea readonly={readonly}></textarea>\n"), ``)                                                                                                                                                                                                                            // attribute-dynamic-boolean <textarea readonly={readonly}></textarea>\n
	// is.Equal(lex("<div a=\"\" b={''} c='' d=\"{''}\" ></div>"), ``)                                                                                                                                                                                                                             // attribute-empty <div a=\"\" b={''} c='' d=\"{''}\" ></div>
	// is.Equal(lex("<div class= ></div>"), ``)                                                                                                                                                                                                                                                    // attribute-empty-error <div class= ></div>
	// is.Equal(lex("<div data-foo='semi:&quot;space:&quot letter:&quote number:&quot1 end:&quot'></div>\n"), ``)                                                                                                                                                                                  // attribute-escaped <div data-foo='semi:&quot;space:&quot letter:&quote number:&quot1 end:&quot'></div>\n
	// is.Equal(lex("<div id='x' class='y'></div>"), ``)                                                                                                                                                                                                                                           // attribute-multiple <div id='x' class='y'></div>
	// is.Equal(lex("<div {id}/>"), ``)                                                                                                                                                                                                                                                            // attribute-shorthand <div {id}/>
	// is.Equal(lex("<div class='foo'></div>"), ``)                                                                                                                                                                                                                                                // attribute-static <div class='foo'></div>
	// is.Equal(lex("<textarea readonly></textarea>"), ``)                                                                                                                                                                                                                                         // attribute-static-boolean <textarea readonly></textarea>
	// is.Equal(lex("<div style=\"color: red;\">red</div>"), ``)                                                                                                                                                                                                                                   // attribute-style <div style=\"color: red;\">red</div>
	// is.Equal(lex("<div style:color={myColor}></div>"), ``)                                                                                                                                                                                                                                      // attribute-style-directive <div style:color={myColor}></div>
	// is.Equal(lex("<div style:color|important={myColor}></div>"), ``)                                                                                                                                                                                                                            // attribute-style-directive-modifiers <div style:color|important={myColor}></div>
	// is.Equal(lex("<div style:color></div>"), ``)                                                                                                                                                                                                                                                // attribute-style-directive-shorthand <div style:color></div>
	// is.Equal(lex("<div style:color=\"red\"></div>\n<div style:color='red'></div>\n<div style:color=red></div>\n<div style:color=\"red{variable}\"></div>\n<div style:color='red{variable}'></div>\n<div style:color=red{variable}></div>\n<div style:color={`template${literal}`}></div>"), ``) // attribute-style-directive-string <div style:color=\"red\"></div>\n<div style:color='red'></div>\n<div style:color=red></div>\n<div style:color=\"red{variable}\"></div>\n<div style:color='red{variable}'></div>\n<div style:color=red{variable}></div>\n<div style:color={`template${literal}`}></div>
	// is.Equal(lex("<Widget foo={42} bind:foo/>"), ``)                                                                                                                                                                                                                                            // attribute-unique-binding-error <Widget foo={42} bind:foo/>
	// is.Equal(lex("<div class='foo' class='bar'></div>"), ``)                                                                                                                                                                                                                                    // attribute-unique-error <div class='foo' class='bar'></div>
	// is.Equal(lex("<div title='foo' {title}></div>"), ``)                                                                                                                                                                                                                                        // attribute-unique-shorthand-error <div title='foo' {title}></div>
	// is.Equal(lex("<div class=foo></div>"), ``)                                                                                                                                                                                                                                                  // attribute-unquoted <div class=foo></div>
	// is.Equal(lex("<button on:click= {foo}>Click</button>\n"), ``)                                                                                                                                                                                                                               // attribute-with-whitespace <button on:click= {foo}>Click</button>\n
	// is.Equal(lex("{#await thePromise}\n\t<p>loading...</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}"), ``)                                                                                                                                                              // await-catch {#await thePromise}\n\t<p>loading...</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}
	// is.Equal(lex("{#await thePromise}\n\t<p>loading...</p>\n{:then theValue}\n\t<p>the value is {theValue}</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}"), ``)                                                                                                          // await-then-catch {#await thePromise}\n\t<p>loading...</p>\n{:then theValue}\n\t<p>the value is {theValue}</p>\n{:catch theError}\n\t<p>oh no! {theError.message}</p>\n{/await}
	// is.Equal(lex("<script>\n\tlet name;\n</script>\n\n<input bind:value={name}>"), ``)                                                                                                                                                                                                          // binding <script>\n\tlet name;\n</script>\n\n<input bind:value={name}>
	// is.Equal(lex("<script>\n\tlet foo;\n</script>\n\n<Widget bind:foo/>"), ``)                                                                                                                                                                                                                  // binding-shorthand <script>\n\tlet foo;\n</script>\n\n<Widget bind:foo/>
	// is.Equal(lex("<!-- a comment -->"), ``)                                                                                                                                                                                                                                                     // comment <!-- a comment -->
	// is.Equal(lex("<!-- svelte-ignore foo bar -->"), ``)                                                                                                                                                                                                                                         // comment-with-ignores <!-- svelte-ignore foo bar -->
	// is.Equal(lex("<svelte:component this=\"{foo ? Foo : Bar}\"></svelte:component>"), ``)                                                                                                                                                                                                       // component-dynamic <svelte:component this=\"{foo ? Foo : Bar}\"></svelte:component>
	// is.Equal(lex("Hello &amp; World"), ``)                                                                                                                                                                                                                                                      // convert-entities Hello &amp; World
	// is.Equal(lex("<p>Hello &amp; World</p>"), ``)                                                                                                                                                                                                                                               // convert-entities-in-element <p>Hello &amp; World</p>
	// is.Equal(lex("<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>"), ``)                                                                                                                                                                                                     // css <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>
	// is.Equal(lex("<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n"), ``)                                                                                                                                                                                                   // css-option-none <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n
	// is.Equal(lex("<svelte:element this=\"div\"></svelte:element>\n<svelte:element this=\"div\" class=\"foo\"></svelte:element>"), ``)                                                                                                                                                           // dynamic-element-string <svelte:element this=\"div\"></svelte:element>\n<svelte:element this=\"div\" class=\"foo\"></svelte:element>
	// is.Equal(lex("<svelte:element this={tag}></svelte:element>\n<svelte:element this={tag} class=\"foo\"></svelte:element>"), ``)                                                                                                                                                               // dynamic-element-variable <svelte:element this={tag}></svelte:element>\n<svelte:element this={tag} class=\"foo\"></svelte:element>
	// is.Equal(lex("<script>\n\timport { onMount } from 'svelte';\n\n\tonMount(() => {\n\t\timport('./foo.js').then(foo => {\n\t\t\tconsole.log(foo.default);\n\t\t});\n\t});\n</script>"), ``)                                                                                                   // dynamic-import <script>\n\timport { onMount } from 'svelte';\n\n\tonMount(() => {\n\t\timport('./foo.js').then(foo => {\n\t\t\tconsole.log(foo.default);\n\t\t});\n\t});\n</script>
	// is.Equal(lex("{#each animals as animal}\n\t<p>{animal}</p>\n{/each}\n"), ``)                                                                                                                                                                                                                // each-block {#each animals as animal}\n\t<p>{animal}</p>\n{/each}\n
	// is.Equal(lex("<script>\n\texport let animals;\n</script>\n\n{#each animals as [key, value, ...rest]}\n\t<p>{key}: {value}</p>\n{/each}\n"), ``)                                                                                                                                             // each-block-destructured <script>\n\texport let animals;\n</script>\n\n{#each animals as [key, value, ...rest]}\n\t<p>{key}: {value}</p>\n{/each}\n
	// is.Equal(lex("{#each animals as animal}\n\t<p>{animal}</p>\n{:else}\n\t<p>no animals</p>\n{/each}\n"), ``)                                                                                                                                                                                  // each-block-else {#each animals as animal}\n\t<p>{animal}</p>\n{:else}\n\t<p>no animals</p>\n{/each}\n
	// is.Equal(lex("{#each animals as animal, i}\n\t<p>{i}: {animal}</p>\n{/each}\n"), ``)                                                                                                                                                                                                        // each-block-indexed {#each animals as animal, i}\n\t<p>{i}: {animal}</p>\n{/each}\n
	// is.Equal(lex("{#each todos as todo (todo.id)}\n\t<p>{todo}</p>\n{/each}\n"), ``)                                                                                                                                                                                                            // each-block-keyed {#each todos as todo (todo.id)}\n\t<p>{todo}</p>\n{/each}\n
	is.Equal(lex("<span attr=\"foo\"></span>\n<span attr='bar'></span>\n"), `LessThan Identifier:"span" Space Identifier:"attr" Equal Quote Text:"foo" Quote GreaterThan LessThanSlash Identifier:"span" GreaterThan Space LessThan Identifier:"span" Space Identifier:"attr" Equal Quote Text:"bar" Quote GreaterThan LessThanSlash Identifier:"span" GreaterThan Space EndOfInput`) // element-with-attribute <span attr=\"foo\"></span>\n<span attr='bar'></span>\n
	// is.Equal(lex("<span attr=\"\"></span>\n<span attr=''></span>\n"), ``)                                                                                                                                                                                                                       // element-with-attribute-empty-string <span attr=\"\"></span>\n<span attr=''></span>\n
	is.Equal(lex("<h1>hello {name}!</h1>\n"), `LessThan Identifier:"h1" GreaterThan Text:"hello " OpenCurly Text:"name" CloseCurly Text:"!" LessThanSlash Identifier:"h1" GreaterThan Space EndOfInput`) // element-with-mustache <h1>hello {name}!</h1>\n
	is.Equal(lex("<span>test</span>"), `LessThan Identifier:"span" GreaterThan Text:"test" LessThanSlash Identifier:"span" GreaterThan EndOfInput`)                                                      // element-with-text <span>test</span>
	is.Equal(lex("<!doctype html>"), `LessThanExclamation Identifier:"doctype" Space Identifier:"html" GreaterThan EndOfInput`)                                                                          // elements <!doctype html>
	// is.Equal(lex("{#await true}\n\t{#each foo as bar}\n{:catch f}\n{/await}"), ``)                                                                                                                                                                                                              // error-catch-before-closing {#await true}\n\t{#each foo as bar}\n{:catch f}\n{/await}
	// is.Equal(lex("{:catch theValue}\n"), ``)                                                                                                                                                                                                                                                    // error-catch-without-await {:catch theValue}\n
	// is.Equal(lex("<!-- an unclosed comment"), ``)                                                                                                                                                                                                                                               // error-comment-unclosed <!-- an unclosed comment
	// is.Equal(lex("<style>\n\tthis is not css\n</style>"), ``)                                                                                                                                                                                                                                   // error-css <style>\n\tthis is not css\n</style>
	// is.Equal(lex("<style>\n\t:global {}\n</style>\n"), ``)                                                                                                                                                                                                                                      // error-css-global-without-selector <style>\n\t:global {}\n</style>\n
	// is.Equal(lex("{#if true}\n\t<li>\n{:else}\n{/if}"), ``)                                                                                                                                                                                                                                     // error-else-before-closing {#if true}\n\t<li>\n{:else}\n{/if}
	// is.Equal(lex("{#if true}\n\t{#await p}\n{:else}\n{/if}"), ``)                                                                                                                                                                                                                               // error-else-before-closing-2 {#if true}\n\t{#await p}\n{:else}\n{/if}
	// is.Equal(lex("<li>\n{:else}"), ``)                                                                                                                                                                                                                                                          // error-else-before-closing-3 <li>\n{:else}
	// is.Equal(lex("{#if true}\n\t{#await foo}\n{:else if false}\n{/if}"), ``)                                                                                                                                                                                                                    // error-else-if-before-closing {#if true}\n\t{#await foo}\n{:else if false}\n{/if}
	// is.Equal(lex("{#if true}\n\t<p>\n{:else if false}\n{/if}"), ``)                                                                                                                                                                                                                             // error-else-if-before-closing-2 {#if true}\n\t<p>\n{:else if false}\n{/if}
	// is.Equal(lex("{#await foo}\n{:then bar}\n\t{:else if}\n{/await}"), ``)                                                                                                                                                                                                                      // error-else-if-without-if {#await foo}\n{:then bar}\n\t{:else if}\n{/await}
	// is.Equal(lex("<span {}></span>"), ``)                                                                                                                                                                                                                                                       // error-empty-attribute-shorthand <span {}></span>
	// is.Equal(lex("<h1 class:={true}>Hello</h1>\n"), ``)                                                                                                                                                                                                                                         // error-empty-classname-binding <h1 class:={true}>Hello</h1>\n
	// is.Equal(lex("<h1 use:>Hello</h1>\n"), ``)                                                                                                                                                                                                                                                  // error-empty-directive-name <h1 use:>Hello</h1>\n
	// is.Equal(lex("{42 = nope}\n"), ``)                                                                                                                                                                                                                                                          // error-illegal-expression {42 = nope}\n
	// is.Equal(lex("<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n\n<style>\n\tdiv {\n\t\tcolor: blue;\n\t}\n</style>"), ``)                                                                                                                                                // error-multiple-styles <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style>\n\n<style>\n\tdiv {\n\t\tcolor: blue;\n\t}\n</style>
	// is.Equal(lex("<h1>Hello {name}!</h1>\n\n<script>"), ``)                                                                                                                                                                                                                                     // error-script-unclosed <h1>Hello {name}!</h1>\n\n<script>
	// is.Equal(lex("<script>\n\n<h1>Hello {name}!</h1>"), ``)                                                                                                                                                                                                                                     // error-script-unclosed-eof <script>\n\n<h1>Hello {name}!</h1>
	// is.Equal(lex("<svelte:self/>"), ``)                                                                                                                                                                                                                                                         // error-self-reference <svelte:self/>
	// is.Equal(lex("<h1>Hello {name}!</h1>\n\n<style>"), ``)                                                                                                                                                                                                                                      // error-style-unclosed <h1>Hello {name}!</h1>\n\n<style>
	// is.Equal(lex("<style>\n\n<h1>Hello {name}!</h1>"), ``)                                                                                                                                                                                                                                      // error-style-unclosed-eof <style>\n\n<h1>Hello {name}!</h1>
	// is.Equal(lex("{#if x}\n\t<svelte:selfdestructive x=\"{x - 1}\"/>\n{/if}"), ``)                                                                                                                                                                                                              // error-svelte-selfdestructive {#if x}\n\t<svelte:selfdestructive x=\"{x - 1}\"/>\n{/if}
	// is.Equal(lex("{#await true}\n\t<li>\n{:then f}\n{/await}"), ``)                                                                                                                                                                                                                             // error-then-before-closing {#await true}\n\t<li>\n{:then f}\n{/await}
	// is.Equal(lex("{:then theValue}\n"), ``)                                                                                                                                                                                                                                                     // error-then-without-await {:then theValue}\n
	// is.Equal(lex("<Component test={{a: 1} />"), ``)                                                                                                                                                                                                                                             // error-unclosed-attribute-self-close-tag <Component test={{a: 1} />
	// is.Equal(lex("<div>"), ``)                                                                                                                                                                                                                                                                  // error-unexpected-end-of-input <div>
	// is.Equal(lex("<d"), ``)                                                                                                                                                                                                                                                                     // error-unexpected-end-of-input-b <d
	// is.Equal(lex("<"), ``)                                                                                                                                                                                                                                                                      // error-unexpected-end-of-input-c <
	// is.Equal(lex("{#if foo}\n\t<p>foo</p>"), ``)                                                                                                                                                                                                                                                // error-unexpected-end-of-input-d {#if foo}\n\t<p>foo</p>
	// is.Equal(lex("</div>"), ``)                                                                                                                                                                                                                                                                 // error-unmatched-closing-tag </div>
	// is.Equal(lex("<p>\n\t<pre>pre tag</pre>\n</p>"), ``)                                                                                                                                                                                                                                        // error-unmatched-closing-tag-autoclose <p>\n\t<pre>pre tag</pre>\n</p>
	// is.Equal(lex("<div>\n\t<p>\n\t<pre>pre tag</pre>\n</div>\n</p>"), ``)                                                                                                                                                                                                                       // error-unmatched-closing-tag-autoclose-2 <div>\n\t<p>\n\t<pre>pre tag</pre>\n</div>\n</p>
	// is.Equal(lex("<input>this is illegal!</input>"), ``)                                                                                                                                                                                                                                        // error-void-closing <input>this is illegal!</input>
	// is.Equal(lex("<svelte:window>contents</svelte:window>"), ``)                                                                                                                                                                                                                                // error-window-children <svelte:window>contents</svelte:window>
	// is.Equal(lex("<svelte:window/>\n<svelte:window/>"), ``)                                                                                                                                                                                                                                     // error-window-duplicate <svelte:window/>\n<svelte:window/>
	// is.Equal(lex("{#if foo}\n\t<svelte:window/>\n{/if}"), ``)                                                                                                                                                                                                                                   // error-window-inside-block {#if foo}\n\t<svelte:window/>\n{/if}
	// is.Equal(lex("<div>\n\t<svelte:window/>\n</div>"), ``)                                                                                                                                                                                                                                      // error-window-inside-element <div>\n\t<svelte:window/>\n</div>
	// is.Equal(lex("<button on:click=\"{() => visible = !visible}\">toggle</button>\n\n{#if visible}\n\t<p>hello!</p>\n{/if}\n"), ``)                                                                                                                                                             // event-handler <button on:click=\"{() => visible = !visible}\">toggle</button>\n\n{#if visible}\n\t<p>hello!</p>\n{/if}\n
	// is.Equal(lex("{#if foo}bar{/if}\n"), ``)                                                                                                                                                                                                                                                    // if-block {#if foo}bar{/if}\n
	// is.Equal(lex("{#if foo}\n\t<p>foo</p>\n{:else}\n\t<p>not foo</p>\n{/if}\n"), ``)                                                                                                                                                                                                            // if-block-else {#if foo}\n\t<p>foo</p>\n{:else}\n\t<p>not foo</p>\n{/if}\n
	// is.Equal(lex("{#if x > 10}\n\t<p>x is greater than 10</p>\n{:else if x < 5}\n\t<p>x is less than 5</p>\n{/if}\n"), ``)                                                                                                                                                                      // if-block-elseif {#if x > 10}\n\t<p>x is greater than 10</p>\n{:else if x < 5}\n\t<p>x is less than 5</p>\n{/if}\n
	// is.Equal(lex("<ul>\n\t<li>a\n\t<li>b\n\t<li>c\n</ul>"), ``)                                                                                                                                                                                                                                 // implicitly-closed-li <ul>\n\t<li>a\n\t<li>b\n\t<li>c\n</ul>
	// is.Equal(lex("<ul>\n\t<li>a\n\t{#if true}\n\t\t<li>b\n\t{/if}\n\t<li>c\n</ul>\n"), ``)                                                                                                                                                                                                      // implicitly-closed-li-block <ul>\n\t<li>a\n\t{#if true}\n\t\t<li>b\n\t{/if}\n\t<li>c\n</ul>\n
	// is.Equal(lex("<span>&nbsp;</span>"), ``)                                                                                                                                                                                                                                                    // nbsp <span>&nbsp;</span>
	// is.Equal(lex("{#if true}\n\t<input>\n{:else}\n{/if}\n\n{#if true}\n\t<br>\n{:else}\n{/if}\n\n{#await true}\n\t<input>\n{:then f}\n{/await}\n\n{#await true}\n\t<br>\n{:then f}\n{/await}"), ``)                                                                                             // no-error-if-before-closing {#if true}\n\t<input>\n{:else}\n{/if}\n\n{#if true}\n\t<br>\n{:else}\n{/if}\n\n{#await true}\n\t<input>\n{:then f}\n{/await}\n\n{#await true}\n\t<br>\n{:then f}\n{/await}
	// is.Equal(lex("<p> {@html raw1} {@html raw2} </p>\n"), ``)                                                                                                                                                                                                                                   // raw-mustaches <p> {@html raw1} {@html raw2} </p>\n
	// is.Equal(lex("{@htmlfoo}\n"), ``)                                                                                                                                                                                                                                                           // raw-mustaches-whitespace-error {@htmlfoo}\n
	// is.Equal(lex("<script>\n\tlet foo;\n</script>\n\n<canvas bind:this={foo}></canvas>"), ``)                                                                                                                                                                                                   // refs <script>\n\tlet foo;\n</script>\n\n<canvas bind:this={foo}></canvas>
	// is.Equal(lex("<script>\n\tlet name = 'world';\n</script>\n\n<h1>Hello {name}!</h1>"), ``)                                                                                                                                                                                                   // script <script>\n\tlet name = 'world';\n</script>\n\n<h1>Hello {name}!</h1>
	// is.Equal(lex("<script>\n\t// TODO write some code\n</script>\n\n<div></div>"), ``)                                                                                                                                                                                                          // script-comment-only <script>\n\t// TODO write some code\n</script>\n\n<div></div>
	// is.Equal(lex("<script>\n\tlet name = 'world';\n\n\t// trailing line comment\n</script>\n\n<h1>Hello {name}!</h1>\n"), ``)                                                                                                                                                                   // script-comment-trailing <script>\n\tlet name = 'world';\n\n\t// trailing line comment\n</script>\n\n<h1>Hello {name}!</h1>\n
	// is.Equal(lex("<script>\n\tlet name = 'world';\n\n\t/*\n\t\ttrailing multiline comment\n\t*/\n</script>\n\n<h1>Hello {name}!</h1>\n"), ``)                                                                                                                                                   // script-comment-trailing-multiline <script>\n\tlet name = 'world';\n\n\t/*\n\t\ttrailing multiline comment\n\t*/\n</script>\n\n<h1>Hello {name}!</h1>\n
	// is.Equal(lex("<div/>"), ``)                                                                                                                                                                                                                                                                 // self-closing-element <div/>
	// is.Equal(lex("{#if depth > 1}\n\t<svelte:self depth='{depth - 1}'/>\n{/if}"), ``)                                                                                                                                                                                                           // self-reference {#if depth > 1}\n\t<svelte:self depth='{depth - 1}'/>\n{/if}
	// is.Equal(lex("<Component><div slot='foo'></div></Component>\n"), ``)                                                                                                                                                                                                                        // slotted-element <Component><div slot='foo'></div></Component>\n
	// is.Equal(lex("<p> {a} {b} : {c} : </p>\n"), ``)                                                                                                                                                                                                                                             // space-between-mustaches <p> {a} {b} : {c} : </p>\n
	// is.Equal(lex("<div {...props}></div>\n"), ``)                                                                                                                                                                                                                                               // spread <div {...props}></div>\n
	// is.Equal(lex("<svelte:head><style></style></svelte:head>"), ``)                                                                                                                                                                                                                             // style-inside-head <svelte:head><style></style></svelte:head>
	// is.Equal(lex("<textarea>\n\t<p>not actually an element. {foo}</p>\n</textarea>"), ``)                                                                                                                                                                                                       // textarea-children <textarea>\n\t<p>not actually an element. {foo}</p>\n</textarea>
	// is.Equal(lex("<textarea>\n\t<p>not actu </textar ally an element. {foo}</p>\n</textare\n\n\n> </textaread >asdf</textarea\n\n\n</textarea\n\n>\n\n"), ``)                                                                                                                                   // textarea-end-tag <textarea>\n\t<p>not actu </textar ally an element. {foo}</p>\n</textare\n\n\n> </textaread >asdf</textarea\n\n\n</textarea\n\n>\n\n
	// is.Equal(lex("<div in:style=\"{{opacity: 0}}\">fades in</div>"), ``)                                                                                                                                                                                                                        // transition-intro <div in:style=\"{{opacity: 0}}\">fades in</div>
	// is.Equal(lex("<div in:fade>fades in</div>"), ``)                                                                                                                                                                                                                                            // transition-intro-no-params <div in:fade>fades in</div>
	// is.Equal(lex("{#each things as 𐊧}\n\t<p>{𐊧}</p>\n{/each}"), ``)                                                                                                                                                                                                                             // unusual-identifier {#each things as 𐊧}\n\t<p>{𐊧}</p>\n{/each}
	// is.Equal(lex("<script>\n\tlet name = 'world';\n</script     \n\n\n\n\n>\n\n<h1>Hello {name}!</h1>"), ``)                                                                                                                                                                                    // whitespace-after-script-tag <script>\n\tlet name = 'world';\n</script     \n\n\n\n\n>\n\n<h1>Hello {name}!</h1>
	// is.Equal(lex("<div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style     \n\n\n\n\n>"), ``)                                                                                                                                                                                      // whitespace-after-style-tag <div>foo</div>\n\n<style>\n\tdiv {\n\t\tcolor: red;\n\t}\n</style     \n\n\n\n\n>
	// is.Equal(lex("\n\n\t\t\t\t<p>just chillin' over here</p>"), ``)                                                                                                                                                                                                                             // whitespace-leading-trailing \n\n\t\t\t\t<p>just chillin' over here</p>
	// is.Equal(lex("<h1>Hello <strong>{name}! </strong><span>How are you?</span></h1>\n"), ``)                                                                                                                                                                                                    // whitespace-normal <h1>Hello <strong>{name}! </strong><span>How are you?</span></h1>\n
}
