// Generates the dom.js files in testdata
import * as svelte from "svelte/compiler";
import path from 'path';
import fs from 'fs';

const dir = path.join(import.meta.dirname, "..", "testdata")
const testdirs = fs.readdirSync(dir)

for (let testdir of testdirs) {
  const absDir = path.join(dir, testdir)
  const inputPath = path.join(absDir, "input.svelte")
  const code = fs.readFileSync(inputPath, 'utf8')
  const dom = svelte.compile(code, {
    filename: inputPath,
    generate: "client",
    css: "external",
    discloseVersion: false,
  })
  const out = "// Generated by `node scripts/generate-dom.js`. Do not edit.\n\n" + dom.js.code
  const name = fs.existsSync(path.join(absDir, "_dom.js")) ? "_dom.js" : "dom.js"
  fs.writeFileSync(path.join(absDir, name), out)
}
