// Generated by `node scripts/generate-dom.js`. Do not edit.

import * as $ from "svelte/internal/client";

var root = $.template(`<h1> </h1>`);

export default function Input($$anchor) {
	let greeting = $.source("hello");

	setInterval(
		() => {
			$.set(greeting, $.get(greeting) + "o");
		},
		1000
	);

	var h1 = root();
	var text = $.child(h1);

	$.reset(h1);

	$.template_effect(() => {
		$.set_attribute(h1, "name", `hello-${$.get(greeting) ?? ""}-cool`);
		$.set_text(text, $.get(greeting));
	});

	$.append($$anchor, h1);
}